import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const scenesDir = path.join(__dirname, 'public', 'scenes');
const metadata = {};

const scenes = fs.readdirSync(scenesDir).filter(f => /^\d+-scene$/.test(f));
for (const scene of scenes) {
  const scenePath = path.join(scenesDir, scene);
  // Match the new webp format generated by Sharp
  const files = fs.readdirSync(scenePath).filter(f => f.endsWith('.webp') || f.endsWith('.jpg') || f.endsWith('.jpeg'));
  
  files.sort();
  
  metadata[scene] = files;
}

fs.writeFileSync(path.join(__dirname, 'public', 'scenes_meta.json'), JSON.stringify(metadata, null, 2));
console.log('Metadata V2 generated referencing active frames successfully!');
